### ISSUE TITLE
Error on run tests

### ISSUE THREAD

**Issue by cotts** [datopian/ckan-integration-tests#15]
Trying to run tests using this module as a dependency, after setting up the environment, it throws the error below.

```
 Error: ENOENT: no such file or directory, scandir 'cypress/fixtures'
  at Object.readdirSync (fs.js:1021:3)
  at file://test-int-tests/node_modules/ckan-integration-tests/index.js:80:10
``` 

How to reproduce: 
-  Set up the environment and test.js configuration.
-  Install required dependencies.
- run the tests

It looks like then the cypress tries to copy the files inside the root project folder, and if it doesn't exist, throws this error.
Just create an empty project root folder called `cypress\fixtures` and `cypress/integration`  and that error disappear.

Is this the expected behavior of this method?

**Comment by cuducos** [comment]
Yes, this is the expected behavior. 
I think this is mostly a matter of documentation. In the `README.md` we say:

> Start with a regular Cypress repository […]

Which assumes the standard directory/files structure of Cypress — but surely this can be enhanced in the docs.
